// <auto-generated />
using System;
using EncurtaLinks.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EncurtaLinks.Data.Migrations
{
    [DbContext(typeof(EncurtaLinksContext))]
    [Migration("20240327192650_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EncurtaLinks.Core.Models.LinkEncurtado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TempoValidadeSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("UltimaParteUrl")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("UrlGerado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UltimaParteUrl")
                        .IsUnique();

                    b.ToTable("LinksEncurtados");
                });
#pragma warning restore 612, 618
        }
    }
}
