// <auto-generated />
using System;
using EncurtaLinks.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EncurtaLinks.Data.Migrations
{
    [DbContext(typeof(EncurtaLinksContext))]
    [Migration("20240303002922_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("EncurtaLinks.Core.Models.LinkEncurtado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("TempoValidadeSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UltimaParteUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlGerado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LinksEncurtados");
                });
#pragma warning restore 612, 618
        }
    }
}
